language: python
python:
  - "3.7"
os:
  - linux
  - osx
  - windows
matrix:
  include:
    - os: linux
      dist: xenial   # required for Python >= 3.7
    - os: osx
    - os: windows
addons:
  apt:
    pacakges:
      - libusb
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update        ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libusb; fi
install:
  - pip3 install numpy
  - pip3 install -r requirements.txt
script:
  - python3 -m unittest
